matrix:
- name: python_comments
  sources:
  - how-to-guides/*.py
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.python:
      comments: true

- name: markdown
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.text
  sources:
  - '/docs/*.md'
