name: Spellcheck
on:
  push:
    branches: [29-41-spellcheck-in-ci]

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Download source
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install python 
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling
        # Install any additional libraries required: additional plugins, documentation building libraries, etc.
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Spell check
      run: |
        python -m pyspelling -c spellcheck.yml
